version: '3'

services:
  db:
    image: postgres:11
    env_file:
        - env_file
    networks: 
        - db_nw
    container_name:
        db
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5

  app:
    build: .
    image: ptt-api:beta
    env_file:
        - env_file
    networks:
        - db_nw
    depends_on:
        - db
    ports:
        - 5000:5000

networks:
    db_nw:
        driver: bridge
