version: 2
jobs:
  build:
    machine: true
    steps:
     - checkout
     # build the application image
     - run: docker-compose up -d
<<<<<<< HEAD

=======
>>>>>>> dcf510e... Update default port for Dockefile
